syntax on

set nocompatible

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

"set background=light
"colorscheme solarized

" Enable viewing man page in vim by ":Man ..."
runtime ftplugin/man.vim
" Set keyword 'K' to use ":Man ..." to view man pages in vim
set keywordprg=:Man

set ruler
set number "show the line number
set laststatus=2 "always displays statusline
set autoindent "inherit the way of indent in the previous line

set expandtab

"provides indent for c
set smartindent
set cindent
set softtabstop=4
set shiftwidth=4

set foldmethod=syntax

set shell=/bin/sh

" Make netrw change dir while exploring
let g:netrw_keepdir = 0

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" Configure ALE
let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = "-std=c++17"

" lh-brackets
let g:usemarks = 0

" VimFold4C
let g:fold_options = {
   \ 'fallback_method' : { 'line_threshold' : 2000, 'method' : 'syntax' },
   \ 'fold_blank': 0,
   \ 'fold_includes': 0,
   \ 'max_foldline_length': 'win',
   \ 'merge_comments' : 1,
   \ 'show_if_and_else': 1,
   \ 'strip_namespaces': 1,
   \ 'strip_template_arguments': 1
   \ }

" Use F8 to open/close tagbar
nmap <F8> :TagbarToggle<CR>

" load vimrcs
runtime! vimrc.d/*.vim
